### ISSUE TITLE
GetAdminMappingsResult in WireMock.Org.Abstractions should contain list of mappings

### ISSUE THREAD

**Issue by roengstrom** [WireMock-Net/WireMock.Net#1021]
### Describe the bug
When running a dedicated instance of Wiremock in a docker container I cannot fetch the configured mappings. It seems like `GetAdminMappingsResult` expects an instance of `Mappings` but according to the [Wiremock API documentation](https://wiremock.org/docs/standalone/admin-api-reference/), this should not be an object but an array. So when I call the method I get an exception:
```
   Newtonsoft.Json.JsonSerializationException : Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'WireMock.Org.Abstractions.Mappings' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path 'mappings', line 2, position 16.
  Stack Trace:
     at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at RestEase.JsonResponseDeserializer.Deserialize[T](String content, HttpResponseMessage response, ResponseDeserializerInfo info)
   at RestEase.Implementation.Requester.Deserialize[T](String content, HttpResponseMessage response, IRequestInfo requestInfo)
   at RestEase.Implementation.Requester.RequestAsync[T](IRequestInfo requestInfo)
```

### Expected behavior:
I expect to not get an exception and instead get an instance of `GetAdminMappingsResult` containing a list of mappings.

### Test to reproduce
- 1 Start docker container running Wiremock
```
docker run -it --rm -p 8080:8080 wiremock/wiremock:3.0.0-1-alpine
```
- 2 Fetch the mappings using the client

```
var wireMockBaseUrl = "http://localhost:8080";
var client = RestClient.For<IWireMockOrgApi>(wireMockBaseUrl);
await client.GetAdminMappingsAsync(null, null);
```

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/1023

**Comment by StefH** [comment]
@roengstrom 

In the beginning I used the openapi-specification from WireMock.Org to generate the classes + api (I was trying to use https://github.com/StefH/RestEase-Client-Generator).

And then I did have to update some code manually to get it working.

---

If it's not too much work, I can try to build a 100% working .NET client, however I need to some and some help from the community for that. (I will also reach out to WireMock.Org)

---

So if you find other issues, please list these here, or create a PR.

**Comment by StefH** [comment]
> @StefH I'll see if I can make time and create a PR. :) Thank you

Do you want to continue your PR on from my branch/PR or should I merge my PR to master so that you can fork and make your own branch?

**Comment by roengstrom** [comment]
@StefH I'm thinking you can merge and I'll work from master in that case.

**Comment by StefH** [comment]
It's merged.
