### ISSUE TITLE
Issue with matching when client uses Host header

### ISSUE THREAD

**Issue by bellorap** [WireMock-Net/WireMock.Net#436]
I'd like to integration test an application that uses the `Host` header in calls to its dependencies. I'm trying to use WireMock to stub these API dependencies, but the existence of the `Host` header is causing the mapping not to match. Here's an example of the problem using NUnit and Flurl:

```csharp
using System;
using Flurl.Http;
using NUnit.Framework;
using WireMock.RequestBuilders;
using WireMock.ResponseBuilders;
using WireMock.Server;
using WireMock.Settings;

namespace Trafi.Vehicles.Tests.Integration.Consumer
{
    public class WireMockTest
    {
        private WireMockServer Server { get; set; }

        [SetUp]
        public void SetUp()
        {
            var wireMockSettings = new FluentMockServerSettings
            {
                Urls = new [] { "http://localhost:5001" }
            };
            Server = WireMockServer.Start(wireMockSettings);
            Server
                .Given(Request.Create()
                    .WithUrl("http://localhost:5001/*")
                    .UsingGet()
                )
                .RespondWith(
                    Response.Create()
                        .WithStatusCode(200)
                        .WithBody(@"{ ""msg"": ""Hello world!"" }")
                );
        }

        [Test]
        public void Test_WithoutHostHeader()
        {
            var result = new FlurlRequest("http://localhost:5001/foo")
                .GetStringAsync()
                .Result;
            Console.WriteLine(result);
        }
        
        [Test]
        public void Test_WithHostHeader()
        {
            var result = new FlurlRequest("http://localhost:5001/foo")
                .WithHeader("Host", "myhost")
                .GetStringAsync()
                .Result;
            Console.WriteLine(result);
        }
        
        [TearDown]
        public void TearDown()
        {
            Server.Stop();
        }
    }
}
```

`Test_WithoutHostHeader` succeeds while `Test_WithHostHeader` throws the following:
```
System.AggregateException : One or more errors occurred. (Call failed with status code 404 (Not Found): GET http://localhost:5001/foo)
  ----> Flurl.Http.FlurlHttpException : Call failed with status code 404 (Not Found): GET http://localhost:5001/foo
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Trafi.Vehicles.Tests.Integration.Consumer.WireMockTest.Test_WithHostHeader() in /Users/pbellora/src/trafi-vehicles-service/Trafi.Vehicles.Tests.Integration/Consumer/WireMockTest.cs:line 45
--FlurlHttpException
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(HttpCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.HttpResponseMessageExtensions.ReceiveString(Task`1 response)
```

Likewise, curling from the command line during test execution shows a similar outcome:
```
$ curl -X GET -H 'Host: myhost' -w '\n%{http_code}\n' 'http://localhost:5001/regions/short'
{"Status":"No matching mapping found"}
404
```

Is there a workaround to this problem? Or do I need to refactor my application to not use the `Host` header during integration tests?

I'm using WireMock.Net version `1.1.10`.

**Comment by StefH** [comment]
You can just use `WithHeader` ?
Like
``` c#
var Server = WireMockServer.Start();
	Server
		.Given(Request.Create()
		    .WithHeader("Host", "*")
			.UsingGet()
		)
		.RespondWith(
			Response.Create()
				.WithStatusCode(200)
				.WithBody(@"{ ""msg"": ""Hello world!"" }")
		);

	string url = Server.Urls.First() + "/foo";
	var result = new FlurlRequest(url)
			.WithHeader("Host", "myhost")
			.GetStringAsync()
			.Result;
	Console.WriteLine(result);
	
	Server.Stop();
```

**Comment by bellorap** [comment]
Hi @StefH, thanks for the quick response. No, unfortunately adding `WithHeader("Host", "*")` still results in the 404 from the test case with the Host header.

**Comment by bellorap** [comment]
Hi @StefH, thanks to your example I believe I narrowed down the problem to `WithUrl`

For example, this solution works:
```
using System;
using System.Linq;
using Flurl.Http;
using NUnit.Framework;
using WireMock.RequestBuilders;
using WireMock.ResponseBuilders;
using WireMock.Server;
using WireMock.Settings;

namespace Trafi.Vehicles.Tests.Integration.Consumer
{
    public class AnotherWireMockTest
    {
        private WireMockServer Server { get; set; }

        [SetUp]
        public void SetUp()
        {
            var wireMockSettings = new FluentMockServerSettings
            {
                Urls = new [] { "http://localhost:5001" }
            };
            Server = WireMockServer.Start(wireMockSettings);
            Server
                .Given(Request
                    .Create()
                    .UsingGet()
                )
                .RespondWith(
                    Response.Create()
                        .WithStatusCode(200)
                        .WithBody(@"{ ""msg"": ""Hello world!"" }")
                );
        }

        [Test]
        public void Test()
        {
            string url = Server.Urls.First() + "/foo";
            var result = new FlurlRequest(url)
                .WithHeader("Host", "myhost")
                .GetStringAsync()
                .Result;
            Console.WriteLine(result);
        }

        [TearDown]
        public void TearDown()
        {
            Server.Stop();
        }
    }
}
```

While this doesn't:
```
using System;
using System.Linq;
using Flurl.Http;
using NUnit.Framework;
using WireMock.RequestBuilders;
using WireMock.ResponseBuilders;
using WireMock.Server;
using WireMock.Settings;

namespace Trafi.Vehicles.Tests.Integration.Consumer
{
    public class AnotherWireMockTest
    {
        private WireMockServer Server { get; set; }

        [SetUp]
        public void SetUp()
        {
            var wireMockSettings = new FluentMockServerSettings
            {
                Urls = new [] { "http://localhost:5001" }
            };
            Server = WireMockServer.Start(wireMockSettings);
            Server
                .Given(Request
                    .Create()
                    .WithUrl("http://localhost:5001/*") // PROBLEM!
                    .UsingGet()
                )
                .RespondWith(
                    Response.Create()
                        .WithStatusCode(200)
                        .WithBody(@"{ ""msg"": ""Hello world!"" }")
                );
        }

        [Test]
        public void Test()
        {
            string url = Server.Urls.First() + "/foo";
            var result = new FlurlRequest(url)
                .WithHeader("Host", "myhost")
                .GetStringAsync()
                .Result;
            Console.WriteLine(result);
        }

        [TearDown]
        public void TearDown()
        {
            Server.Stop();
        }
    }
}
```

Am I using `WithUrl` correctly? In practice, I think I need it to match requests to different ports with different mappings.

**Comment by StefH** [comment]
WithUrl can be used. However in your case I think that removing WithUrl and/or replacing with WithPath would be better.

Take a look at the Wiki or unit tests for more examples.

**Comment by bellorap** [comment]
@StefH I'm not sure I understand your answer. Is the last snipped posted above expected to work? If not, can you please explain why? Otherwise, would it make sense to open a bug for this behavior?

**Comment by StefH** [comment]
The `WithUrl` works as expected. However, because you overwrite the **host**, the url in WireMock is changed to that one.
So you need code like this:
``` c#
var wireMockSettings = new FluentMockServerSettings
            {
                Urls = new[] { "http://localhost:5001" },
                // AllowPartialMapping = true,
                Logger = new WireMockConsoleLogger()
            };
            var Server = WireMockServer.Start(wireMockSettings);
            Server
                .Given(Request
                    .Create()
                    .WithHeader("host", "*") /// <------ 
                    .WithUrl("http://myhost/*") // <------
                    .UsingGet()
                )
                .RespondWith(
                    Response.Create()
                        .WithStatusCode(200)
                        .WithBody(@"{ ""msg"": ""Hello world!"" }")
                );

            string url = Server.Urls.First() + "/foo";
            var result = new FlurlRequest(url)
                .WithHeader("Host", "myhost")
                .GetStringAsync()
                .Result;
            Console.WriteLine(result);
```

Note that adding the console logger and setting AllowPartialMapping = true can help you detect why a mapping is not 100% matching.

**Comment by bellorap** [comment]
@StefH That makes sense, thanks for explaining! I also didn't notice `AllowPartialMapping` - that's helpful!
