### ISSUE TITLE
docker image netstandard2.0 failed to start due to unable to configure HTTPS endpoint

### ISSUE THREAD

**Issue by yunj** [WireMock-Net/WireMock.Net#466]
[Here](https://github.com/WireMock-Net/WireMock.Net/wiki/Using-HTTPS-%28SSL%29#http-ssl) documents that when using netstandard, WireMock.Net uses a self signed certificate to host https urls. But when docker run `sheyenrath/wiremock.net:1.2.6` with `--Urls http://localhost:9091 https://localhost:9443`, it failed to start due to the error **Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found**.

```
05/15/2020 21:23:38 [Debug] : WireMock.Net server settings {
  "Port": null,
  "UseSSL": null,
  "StartAdminInterface": true,
  "ReadStaticMappings": true,
  "WatchStaticMappings": false,
  "WatchStaticMappingsInSubdirectories": false,
  "ProxyAndRecordSettings": null,
  "Urls": [
    "http://localhost:9091",
    "https://localhost:9443"
  ],
  "StartTimeout": 10000,
  "AllowPartialMapping": false,
  "AdminUsername": null,
  "AdminPassword": null,
  "RequestLogExpirationDuration": null,
  "MaxRequestLogCount": null,
  "AllowCSharpCodeMatcher": false,
  "AllowBodyForAllHttpMethods": false,
  "AllowOnlyDefinedHttpStatusCodeInResponse": false,
  "DisableJsonBodyParsing": false,
  "DisableRequestBodyDecompressing": null
}
05/15/2020 21:23:39 [Info] : WireMock.Net server using netstandard2.0
Application startup exception: System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate c
ould not be found.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
   at WireMock.Owin.AspNetCoreSelfHost.<>c.<StartAsync>b__19_3(ListenOptions listenOptions)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.Listen(IPEndPoint endPoint, Action`1 configure)
   at WireMock.Owin.AspNetCoreSelfHost.<StartAsync>b__19_2(KestrelServerOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.CreateServiceContext(IOptions`1 options, ILoggerFactory loggerFactory)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer..ctor(IOptions`1 options, ITransportFactory transportFactory, ILoggerFactory loggerFactory)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureServer()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```

Does it mean I need to build a new image with certificate installed? Thanks a lot!

**Comment by StefH** [comment]
What I normally do is just run and start the container in Azure with no additional port or url settings.
Only these parameters `--StartAdminInterface true --AdminUsername xxx--AdminPassword xxx --UseSSL true --WireMockLogger WireMockConsoleLogger`

When running in Azure I can access the service at http and https.

**Comment by yunj** [comment]
Hi @StefH , thanks very much for your reply.

I can only run the Wiremock.Net container on a normal computer. I tried `--UseSSL` but seems not working and the server settings show `UseSSL:null`.

```
PS C:\wiremock.net> docker run sheyenrath/wiremock.net:1.2.6 --StartAdminInterface true --UseSSL true --WireMockLogger WireMockConsoleLogger
05/16/2020 08:14:27 [Info] : WireMock.Net by Stef Heyenrath (https://github.com/WireMock-Net/WireMock.Net)
05/16/2020 08:14:28 [Debug] : WireMock.Net server settings {
  "Port": null,
  "UseSSL": null,
  "StartAdminInterface": true,
  "ReadStaticMappings": false,
  "WatchStaticMappings": false,
  "WatchStaticMappingsInSubdirectories": false,
  "ProxyAndRecordSettings": null,
  "Urls": [
    "http://*:80"
  ],
  "StartTimeout": 10000,
  "AllowPartialMapping": false,
  "AdminUsername": null,
  "AdminPassword": null,
  "RequestLogExpirationDuration": null,
  "MaxRequestLogCount": null,
  "AllowCSharpCodeMatcher": false,
  "AllowBodyForAllHttpMethods": false,
  "AllowOnlyDefinedHttpStatusCodeInResponse": false,
  "DisableJsonBodyParsing": false,
  "DisableRequestBodyDecompressing": null
}
05/16/2020 08:14:28 [Info] : WireMock.Net server using netstandard2.0
Hosting environment: Production
Content root path: /app/
Now listening on: http://0.0.0.0:80
05/16/2020 08:14:28 Press Ctrl+C to shut down
05/16/2020 08:14:28 WireMock.Net server running
```

**Comment by StefH** [comment]
What you need to do is provide the URLs as you did before (`--Urls http://localhost:9091 https://localhost:9443`)

And then take a look at this article: https://www.vivienfabing.com/docker/2019/10/03/docker-aspnetcore-container-and-https.html
I think this describes how to solve your issue. However, I did not yet test this myself.

**Comment by yunj** [comment]
Thanks @StefH for your reply. For the container in Azure, what are the values for `ASPNETCORE_URLS`, `ASPNETCORE_HTTPS_PORT`, `ASPNETCORE_Kestrel__Certificates__Default__Path`?

**Comment by StefH** [comment]
When deploying WireMock.Net to Azure, I just use this deployment:

![image](https://user-images.githubusercontent.com/249938/82561291-6a964a00-9b73-11ea-8ff2-7782cb3eab8b.png)


``` yml
steps:
- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy Docker Container to Linux Web App'
  inputs:
    azureSubscription: '$(Parameters.ConnectedServiceName)'
    appType: '$(Parameters.WebAppKind)'
    WebAppName: '$(Parameters.WebAppName)'
    DockerNamespace: '$(Parameters.DockerNamespace)'
    DockerRepository: '$(Parameters.DockerRepository)'
    DockerImageTag: '$(Build.BuildId)'
    StartupCommand: '$(Parameters.StartupCommand)'
```


And the only things I provide are:
`--StartAdminInterface true --AdminUsername xxx --AdminPassword xxx --UseSSL true --WireMockLogger WireMockConsoleLogger`

Now I can access wiremock via https
Example:
https://wiremock-090dee8d-d6dc-4754-bd61-8372acd20ded.azurewebsites.net/

**Comment by StefH** [comment]
@yunj 
Does this answer your question?

**Comment by yunj** [comment]
@StefH thanks very much. We decided to use http.
