### ISSUE TITLE
How to send a request to a specific URL after sending response

### ISSUE THREAD

**Issue by samiransaha** [WireMock-Net/WireMock.Net#589]
The java version of wiremock supports Post-serve actions mentioned here http://wiremock.org/docs/extending-wiremock/.
By using this we can send request to a specific URL after serving mocked response to a request. Is it possible to with wiremock.net? if yes, can we configure it via JSON and does it support authentication?

**Comment by StefH** [comment]
You are looking for a hook / callback which will be triggered after the response has been returned?

**Comment by samiransaha** [comment]
Yes. Hook/Callback would be generic. But in addition, if we can have some predefined post-serve hook like sending request to URL and surface it via JSON configuration, so that one can configure it via JSON mapping files then it would be great.

**Comment by StefH** [comment]
Dear @samiransaha, I did update your question with some code formatting so that it it's better readable.

I think this can be implemented, however it will take some effort.

And maybe instead of letting the user define the content, it's maybe easier to just forward the complete request and response to that callback hook. So that all data is present.

``` json
  "Hook": {
        "Request": {
            "Url": "http://auditmyoperation.com",
           "Method" : "Post",
           "Headers": {
             "Authorization": " skslsljd ",
             "Content-Type": "application / json"
           }
    }
```

**Comment by samiransaha** [comment]
Thanks @StefH.
Glad to know.
I think there should be an option to send custom request body while sending request in hook along with the option to send complete request body received the way have mentioned.

**Comment by StefH** [comment]
@samiransaha 
I've created a preview nuget on myget:, can you please test vesion WireMock.Net.1.4.7-ci-14761 ?

Only Body or BodyAsJson is supported. No transformation (yet)

example
``` json
{
    "Guid": "755384f9-2252-433d-ae8b-445b9f1cc729",
    "Priority": 0,
    "Request": {
        "Path": {
            "Matchers": [
                {
                    "Name": "WildcardMatcher",
                    "Pattern": "/wh"
                }
            ]
        },
        "Methods": [
            "POST"
        ]
    },
    "Response": {
        "Body": "<xml>ok</xml>",
        "Headers": {
            "Content-Type": "application/xml"
        }
    },
    "Webhook": {
        "Request": {
            "Url": "http://{{wm_hostname}}/post",
            "Method": "POST",
            "Headers": {
                "x": "x-value"
            },
            "Body": "ok?"
        }

    }
}
```

**Comment by StefH** [comment]
@samiransaha A new version `WireMock.1.4.7-ci-14768` should now also support transformation.

Add `"UseTransformer": true`

**Comment by samiransaha** [comment]
Thanks @StefH, I will check it. 
Another thing not related to webhook, I wanted to know is it possible to configure delay before sending response via JSON?

**Comment by samiransaha** [comment]
I am using the wiremock as dotnet tool. How to get your CI version for that?

**Comment by StefH** [comment]
> 
> 
> Thanks @StefH, I will check it.
> Another thing not related to webhook, I wanted to know is it possible to configure delay before sending response via JSON or not sending any response entirely?
> Something like this in java version of wiremock http://wiremock.org/docs/simulating-faults/

See https://github.com/WireMock-Net/WireMock.Net/wiki/Faults

**Comment by StefH** [comment]
> 
> 
> I am using the wiremock as dotnet tool. How to get your CI version for that?

it's on the same MyGet feed:
https://www.myget.org/feed/wiremock-net/package/nuget/dotnet-WireMock

``` sh
PM> Install-Package dotnet-WireMock -Version 1.4.7-ci-14780 -Source https://www.myget.org/F/wiremock-net/api/v3/index.json 
```

**Comment by samiransaha** [comment]
Can we add Faults like no response at all?
Thanks @StefH, sorry I missed that in myget link.

**Comment by StefH** [comment]
@samiransaha Did you have time to test it ?

**Comment by StefH** [comment]
@samiransaha Did you have to test?

**Comment by StefH** [comment]
@samiransaha Can you please test this?

**Comment by samiransaha** [comment]
@StefH , Hey sorry for delay, I got sick, and was not able to catch up my emails. I will test this today, and let you know.

**Comment by samiransaha** [comment]
Hi @StefH,

I used following rule it didn't work for me looks like.
I got the response, but the webhook request generation failed.
And I see following error is console. Any Idea?
```
2021-03-16T00:16:20 fail: [0]
      Sending message to Webhook Mapping 'b3418573-223b-46b7-a652-e375a6767b4d' failed. Exception: System.Net.Http.HttpRequestException: Cannot assign requested address (localhost:8989)
       ---> System.Net.Sockets.SocketException (99): Cannot assign requested address
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
         at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
         at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
         at WireMock.Owin.WireMockMiddleware.SendToWebhookAsync(IMapping mapping, RequestMessage request, ResponseMessage response) in /_/src/WireMock.Net/Owin/WireMockMiddleware.cs:line 200
```


```
{
  "Request": {
	  "Path": {
		"Matchers": [
			{
				"Name": "WildcardMatcher",
				"Pattern": "/api/user/mock_user_hook",
				"IgnoreCase": false
			}
		]
	},
	"Methods": [
	  "get"
	]
  },
  "Response": {
	"StatusCode": 200,
	"Headers": {
	  "Content-Type": "application/json",
	},
	"Body": "{
		\"Id\" : \"mock_user_cess\",
		\"Name\": \"Mock User\",
		\"City\": \"London\"
	}",
	"UseTransformer": true
  },
  "Webhook": {
        "Request": {
            "Url": "http://localhost:8989/api/saas/subscriptions/order_delete_failure_403",
            "Method": "delete",
            "Headers": {
                "mock-header": "hook-mock"
            }
        }
    }
}
```

**Comment by StefH** [comment]
Very strange, according to WIKI it looks fine. (https://github.com/WireMock-Net/WireMock.Net/wiki/Webhook)

See also this unit tests (https://github.com/WireMock-Net/WireMock.Net/blob/819629125ce3f34e71a31ba6a8825a13b0b8adb1/test/WireMock.Net.Tests/WireMockServer.WebhookTests.cs)

Did you try another address?

**Comment by samiransaha** [comment]
Hey it worked now, there was issue in network issue with that port for that time being.

**Comment by StefH** [comment]
@samiransaha Thanks for testing.
I'll merge the PR and create a new official NuGet version today or at most tomorrow.
