### ISSUE TITLE
generate randow value alphanumeric string of length to be picked up from request.body parameter

### ISSUE THREAD

**Issue by nilimamoh** [WireMock-Net/WireMock.Net#780]
My requirement is to make length accept the parameter i supplied from request body for the json path & generate a random alphanumeric string of the given length
but below is not working getting exception : is there a synax issue ? can this be done

{{{randomValue (length jsonPath request.body '$.otpParams.length') type='ALPHANUMERIC'}}}

	<title>Error 500 wiremock.com.google.common.util.concurrent.UncheckedExecutionException:
		wiremock.com.github.jknack.handlebars.HandlebarsException: inline@6e008506:1:100: could not find helper:
		&apos;length&apos;
		{{randomValue type=&apos;UUID&apos;}}&quot;,&quot;callerTransactionId&quot;:&quot;caller325782532086010&quot;,&quot;token&quot;:&quot;{{{randomValue (length jsonPath request.body &apos;$.otpParams.length&apos;) type=&apos;ALPHANUMERIC&apos;}}}

**Comment by nilimamoh** [comment]
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1" />
	<title>Error 500 wiremock.com.google.common.util.concurrent.UncheckedExecutionException:
		wiremock.com.github.jknack.handlebars.HandlebarsException: inline@6e008506:1:100: could not find helper:
		&apos;length&apos;
		{{randomValue type=&apos;UUID&apos;}}&quot;,&quot;callerTransactionId&quot;:&quot;caller325782532086010&quot;,&quot;token&quot;:&quot;{{{randomValue (length jsonPath request.body &apos;$.otpParams.length&apos;) type=&apos;ALPHANUMERIC&apos;}}}
		^
	</title>
</head>

<body>
	<h2>HTTP ERROR 500 wiremock.com.google.common.util.concurrent.UncheckedExecutionException:
		wiremock.com.github.jknack.handlebars.HandlebarsException: inline@6e008506:1:100: could not find helper:
		&apos;length&apos;
		{{randomValue type=&apos;UUID&apos;}}&quot;,&quot;callerTransactionId&quot;:&quot;caller325782532086010&quot;,&quot;token&quot;:&quot;{{{randomValue (length jsonPath request.body &apos;$.otpParams.length&apos;) type=&apos;ALPHANUMERIC&apos;}}}
		^
	</h2>
	<table>
		<tr>
			<th>URI:</th>
			<td>/api/v1/generateOTP</td>
		</tr>
		<tr>
			<th>STATUS:</th>
			<td>500</td>
		</tr>
		<tr>
			<th>MESSAGE:</th>
			<td>wiremock.com.google.common.util.concurrent.UncheckedExecutionException:
				wiremock.com.github.jknack.handlebars.HandlebarsException: inline@6e008506:1:100: could not find helper:
				&apos;length&apos;
				{{randomValue type=&apos;UUID&apos;}}&quot;,&quot;callerTransactionId&quot;:&quot;caller325782532086010&quot;,&quot;token&quot;:&quot;{{{randomValue (length jsonPath request.body &apos;$.otpParams.length&apos;) type=&apos;ALPHANUMERIC&apos;}}}
				^
			</td>
		</tr>
		<tr>
			<th>SERVLET:</th>
			<td>com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet-795509d9</td>
		</tr>
		<tr>
			<th>CAUSED BY:</th>
			<td>wiremock.com.google.common.util.concurrent.UncheckedExecutionException:
				wiremock.com.github.jknack.handlebars.HandlebarsException: inline@6e008506:1:100: could not find helper:
				&apos;length&apos;
				{{randomValue type=&apos;UUID&apos;}}&quot;,&quot;callerTransactionId&quot;:&quot;caller325782532086010&quot;,&quot;token&quot;:&quot;{{{randomValue (length jsonPath request.body &apos;$.otpParams.length&apos;) type=&apos;ALPHANUMERIC&apos;}}}
				^
			</td>
		</tr>
		<tr>
			<th>CAUSED BY:</th>
			<td>wiremock.com.github.jknack.handlebars.HandlebarsException: inline@6e008506:1:100: could not find helper:
				&apos;length&apos;
				{{randomValue type=&apos;UUID&apos;}}&quot;,&quot;callerTransactionId&quot;:&quot;caller325782532086010&quot;,&quot;token&quot;:&quot;{{{randomValue (length jsonPath request.body &apos;$.otpParams.length&apos;) type=&apos;ALPHANUMERIC&apos;}}}
				^
			</td>
		</tr>
	</table>
	<h3>Caused by:</h3>
	<pre>wiremock.com.google.common.util.concurrent.UncheckedExecutionException: wiremock.com.github.jknack.handlebars.HandlebarsException: inline@6e008506:1:100: could not find helper: &apos;length&apos;
{{randomValue type=&apos;UUID&apos;}}&quot;,&quot;callerTransactionId&quot;:&quot;caller325782532086010&quot;,&quot;token&quot;:&quot;{{{randomValue (length jsonPath request.body &apos;$.otpParams.length&apos;) type=&apos;ALPHANUMERIC&apos;}}}
                                                                                                    ^

	at wiremock.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2055)
	at wiremock.com.google.common.cache.LocalCache.get(LocalCache.java:3966)
	at wiremock.com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4863)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.TemplateEngine.getTemplate(TemplateEngine.java:96)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.ResponseTemplateTransformer.transform(ResponseTemplateTransformer.java:104)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings.applyTransformations(InMemoryStubMappings.java:102)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings.serveFor(InMemoryStubMappings.java:84)
	at com.github.tomakehurst.wiremock.core.WireMockApp.serveStubFor(WireMockApp.java:226)
	at com.github.tomakehurst.wiremock.http.StubRequestHandler.handleRequest(StubRequestHandler.java:57)
	at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:69)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:142)
	at wiremock.javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at wiremock.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at wiremock.org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:763)
	at wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at wiremock.org.eclipse.jetty.server.Server.handle(Server.java:516)
	at wiremock.org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	at wiremock.org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at wiremock.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at wiremock.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at wiremock.org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at wiremock.org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at wiremock.org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at wiremock.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at wiremock.org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: wiremock.com.github.jknack.handlebars.HandlebarsException: inline@6e008506:1:100: could not find helper: &apos;length&apos;
{{randomValue type=&apos;UUID&apos;}}&quot;,&quot;callerTransactionId&quot;:&quot;caller325782532086010&quot;,&quot;token&quot;:&quot;{{{randomValue (length jsonPath request.body &apos;$.otpParams.length&apos;) type=&apos;ALPHANUMERIC&apos;}}}
                                                                                                    ^

	at wiremock.com.github.jknack.handlebars.internal.HbsErrorReporter.syntaxError(HbsErrorReporter.java:93)
	at wiremock.com.github.jknack.handlebars.internal.HbsParserFactory$1$1.reportError(HbsParserFactory.java:109)
	at wiremock.com.github.jknack.handlebars.internal.TemplateBuilder.newVar(TemplateBuilder.java:407)
	at wiremock.com.github.jknack.handlebars.internal.TemplateBuilder.visitSubParamExpr(TemplateBuilder.java:487)
	at wiremock.com.github.jknack.handlebars.internal.HbsParser$SubParamExprContext.accept(HbsParser.java:1816)
	at wiremock.com.github.jknack.handlebars.internal.antlr.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at wiremock.com.github.jknack.handlebars.internal.TemplateBuilder.params(TemplateBuilder.java:473)
	at wiremock.com.github.jknack.handlebars.internal.TemplateBuilder.visitTvar(TemplateBuilder.java:342)
	at wiremock.com.github.jknack.handlebars.internal.TemplateBuilder.visitTvar(TemplateBuilder.java:83)
	at wiremock.com.github.jknack.handlebars.internal.HbsParser$TvarContext.accept(HbsParser.java:1160)
	at wiremock.com.github.jknack.handlebars.internal.antlr.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at wiremock.com.github.jknack.handlebars.internal.TemplateBuilder.visit(TemplateBuilder.java:153)
	at wiremock.com.github.jknack.handlebars.internal.TemplateBuilder.visitStatement(TemplateBuilder.java:718)
	at wiremock.com.github.jknack.handlebars.internal.TemplateBuilder.visitStatement(TemplateBuilder.java:83)
	at wiremock.com.github.jknack.handlebars.internal.HbsParser$StatementContext.accept(HbsParser.java:303)
	at wiremock.com.github.jknack.handlebars.internal.antlr.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at wiremock.com.github.jknack.handlebars.internal.TemplateBuilder.visit(TemplateBuilder.java:153)
	at wiremock.com.github.jknack.handlebars.internal.TemplateBuilder.visitBody(TemplateBuilder.java:686)
	at wiremock.com.github.jknack.handlebars.internal.TemplateBuilder.visitTemplate(TemplateBuilder.java:517)
	at wiremock.com.github.jknack.handlebars.internal.TemplateBuilder.visitTemplate(TemplateBuilder.java:83)
	at wiremock.com.github.jknack.handlebars.internal.HbsParser$TemplateContext.accept(HbsParser.java:162)
	at wiremock.com.github.jknack.handlebars.internal.antlr.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at wiremock.com.github.jknack.handlebars.internal.TemplateBuilder.visit(TemplateBuilder.java:153)
	at wiremock.com.github.jknack.handlebars.internal.HbsParserFactory$1.parse(HbsParserFactory.java:113)
	at wiremock.com.github.jknack.handlebars.cache.NullTemplateCache.get(NullTemplateCache.java:54)
	at wiremock.com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:575)
	at wiremock.com.github.jknack.handlebars.Handlebars.compileInline(Handlebars.java:535)
	at wiremock.com.github.jknack.handlebars.Handlebars.compileInline(Handlebars.java:515)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.HandlebarsOptimizedTemplate.uncheckedCompileTemplate(HandlebarsOptimizedTemplate.java:56)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.HandlebarsOptimizedTemplate.&lt;init&gt;(HandlebarsOptimizedTemplate.java:51)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.TemplateEngine.lambda$getTemplate$0(TemplateEngine.java:96)
	at wiremock.com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4868)
	at wiremock.com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533)
	at wiremock.com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282)
	at wiremock.com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159)
	at wiremock.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
	... 40 more
</pre>

</body>

</html>

**Comment by StefH** [comment]
@nilimamoh 
This issue should be listed for https://wiremock.org/

(This repository is for the .NET version)
